name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      # - name: Run Snyk Security Scan
      #   uses: snyk/actions/node@v3
      #   with:
      #     command: test
      #   env:
      #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # - name: Run SonarCloud Analysis
      #   uses: sonarsource/sonarcloud-github-action@v1
      #   with:
      #     projectKey: ${{ secrets.SONAR_PROJECT_KEY }}
      #     organization: ${{ secrets.SONAR_ORGANIZATION }}
      #     token: ${{ secrets.SONAR_TOKEN }}

      # - name: Run Fortify Scan
      #   run: |
      #     curl -o fortify-scan.sh https://fortify.example.com/scan.sh
      #     chmod +x fortify-scan.sh
      #     ./fortify-scan.sh
      #   env:
      #     FORTIFY_API_KEY: ${{ secrets.FORTIFY_API_KEY }}

      - name: Run Tests
        run: npm test